/*
 * FakeStudentNames.h
 *
 *  Created on: Feb 11, 2020
 *      Author: myles
 */

#include <string>

#ifndef SRC_MAIN_FAKESTUDENTNAMES_H_
#define SRC_MAIN_FAKESTUDENTNAMES_H_

using namespace std;

string names[603] = { "Christopher Ferguson", "Nicholas Rees", "Simon Burgess",
		"Evan Carr", "Donna Paige", "Ramone Garcia", "Anthony North",
		"Emma Langdon", "Xavier Flynn", "Vladimir Petrov", "Christian Mackay",
		"Alexander Stewart", "Carl Allan", "Julia Russell", "Adam Abraham",
		"Jane Bailey", "Ian Walker", "Gabrielle Walker", "Matthew Cilibraise",
		"Wally Payne", "Sofia Kozlov", "Elizabeth Marquise", "Penelope Oliver",
		"Jasmine Short", "Stewart Forsyth", "Andrew Bower", "Yvonne Simpson",
		"Tyler Smith", "Caleb Johnston", "Steven Moore", "Kylie Manning",
		"Daniel Hernandez", "Rick Buckland", "Jeff Hughes", "Trevor Watson",
		"Alan Hamilton", "Josiah Edmunds", "Allen Langdon", "Carl Davidson",
		"Jacob Fraser", "Mateo Forsyth", "Belinda Louis", "Grace Turner",
		"Nolan Sanchez", "Piers Chapman", "Tracey Young", "Nathan Lambert",
		"Steven Black", "Amelia Marshall", "Cooper Smith", "Fiona Churchill",
		"Grace Brown", "Sean Rogers", "Dylan Chapman", "Anthony Simpson",
		"Edward Jones", "Heather Henderson", "Wanda Young", "Lucas Newman",
		"Leah Hudson", "Anthony Hughes", "Lisa Thompson", "Nicholas Avery",
		"William Parr", "Cristi Deleo", "Tim Peters", "Anthony Davies",
		"Dominic Ince", "Winston Berry", "Justin Brown", "Morty Baxter",
		"Felicity King", "Rebecca Coleman", "Zack Wilcox", "Colin Coleman",
		"Simon Sutherland", "Peter Miller", "Jane Tucker", "Caroline Powell",
		"Maggie Wallace", "Audrey Jackson", "Jonathan Young", "Oliver Smith",
		"Trevor Robertson", "Sophie Cornish", "Leonard Hamilton",
		"Claire Clark", "Blake Robertson", "Lily Murray", "Chloe Springer",
		"Una Watson", "Lydia Stone", "Ruth King", "James Quincy", "Tracey Gill",
		"Jessica Clark", "Donna Nash", "Jonah Terry", "Chris Coleman",
		"Tommy Brown", "Sean Robertson", "Michael Bailey", "Andrea Grant",
		"Harrison Martin", "Jason Sharp", "Asher Grey", "Neil North",
		"Nick Glover", "Eric Underwood", "Christopher Lee", "Trevor Ogden",
		"Jake Springer", "Faith North", "Karen Simpson", "Chase Langdon",
		"Samantha King", "Zoe Jones", "Ruby Roberts", "Juan Rodriguez",
		"Colin Butler", "Conner Churchill", "Henry Clarkson", "Roberto Clark",
		"Bella Hudson", "Nicola Davies", "Caroline Harris", "Lucian Bower",
		"Oliver Scott", "Edward Lawrence", "Beverly Dunn", "Eric Fisher",
		"Oliver Chapman", "Robert Walsh", "Helen Welch", "Emily May",
		"Steven Knox", "Wanda Gill", "Mary Martin", "Peter Parr",
		"Stacy Johnson", "Will Rose", "James Forrester", "Joan Blake",
		"Christopher Baker", "Ian Hill", "Dorothy Skinner", "Trevor Harris",
		"Sarah Scott", "Benjamin Jones", "Jennifer Lewis", "Ruth Nash",
		"Jeremy Evans", "Alexandra Bell", "Leo Alsop", "Max Russell",
		"Alex Kerr", "Lucas Morgan", "Frank Mitchell", "Sean Parsons",
		"Ryan Tucker", "Adrian Ross", "Myles Colina", "David Hamilton",
		"Carolina Oliver", "Sandra Mitchell", "Andrew Wilson", "Howard Mill",
		"Matt James", "Abigail Hardacre", "Jonah Greene", "Joshua Chapman",
		"Luke Coleman", "Karen Clarkson", "Sophie Walker", "Oliver Paterson",
		"Preston Vance", "Joe Reid", "Robert Reid", "Lily Pullman",
		"Rebecca Jones", "Jacob Alsop", "Scott Avery", "Lucas Avery",
		"John Howard", "Wendy Brown", "Lillian Russell", "Paxton Morgan",
		"Ava Pullman", "Yvonne Sanderson", "Sam Cameron", "Joe Clarkson",
		"Rose Rockwell", "Steven Arnold", "Alexander Kelly", "Cameron Smith",
		"Andrew Scott", "Harry Newman", "Melanie Simpson", "Vanessa Ball",
		"Alison Metcalfe", "Benjamin Kerr", "Paul Wright", "Ruth Paige",
		"Cho Quain", "Una McDonald", "Sally Arnold", "Anne Langdon",
		"Justin Jones", "Deirdre Walker", "Connor Russellv",
		"Katherine Rutherford", "Andrea Chapman", "Justin Walker",
		"Opal Graystone", "Colin Mackenzie", "Felicity Ince", "Irene Greene",
		"John Patersonv", "Gabrielle Brown", "Joseph Glover", "Sarah Pullman",
		"James Piper", "Ezra Carr", "Jasmine North", "Maria Black",
		"Jasmine Mackenzie", "Justin Wilkins", "Carol Wilkins",
		"Christopher Hill", "Chase Russell", "Tyler Morrison",
		"Hernando Lambert", "Dan Walsh", "Cliff North", "Blake Underwood",
		"Alison Ince", "SueEllen Springer", "Ruth Manning", "Jacob Anderson",
		"Deirdre Reid", "Kimberly Hardacre", "Virginia Lee", "Evan Abraham",
		"Stewart Buckland", "Sean McDonald", "Katherine Nash",
		"Michael Russell", "Tracey Nash", "Carol Short", "Matt Turner",
		"Diane Hudson", "Kevin Marcy", "Stephanie Pullman", "Alison Bell",
		"Isaac Cornish", "Steven Reid", "Megan Roberts", "Eric Slater",
		"Carol Roberts", "Boris Morgan", "Chloe Butler", "Leah McLean",
		"Grace Rees", "Caroline Arnold", "Victor Paterson", "Barry Quinn",
		"Christian Wright", "Oliver Welch", "Eric Jackson", "Megan Chapman",
		"Simon Wallace", "Penny Turner", "Tracey Robertson", "Emily Arnold",
		"Nathan Johnston", "Stephen Roberts", "Dorothy Piper",
		"Jennifer Metcalfe", "Christian Langdon", "Christopher Arnold",
		"Neil MacDonald", "Penny Parsons", "Owen Manning", "Andrew Avery",
		"Emma Churchill", "Ian Terry", "Brandon Terry", "Liam Parr",
		"Jennifer Welch", "Yvonne Parr", "Nicole Hart", "Donna Ellison",
		"Simon Rampling", "Anna Arnold", "Diane Randall", "Jonathan McDonald",
		"Julia Anderson", "Warren Bailey", "Jessica Wallace",
		"Katherine Thomson", "Lucas Butler", "Ryan Rutherford",
		"Samantha North", "Cameron Morrison", "Michelle Butler",
		"Bernadette Miller", "Liam Lyman", "Vanessa Slater", "Victoria Simpson",
		"Boris Cornish", "Keith Newman", "Carl Lawrence", "Colin Dickens",
		"Luke James", "Caroline Grant", "Frank Gray", "Vanessa Allan",
		"Sean Baker", "Frank Mills", "Rachel Mackenzie", "Stephen Sanderson",
		"Kimberly Vaughan", "Warren Vaughan", "Sebastian Lyman",
		"Cameron Young", "Harry McGrath", "Thomas Langdon", "Benjamin Turner",
		"Anthony Murray", "Anna Miller", "Kevin Black", "Chloe Nolan",
		"Michelle Hodges", "Dominic Bower", "Simon Paige", "Sebastian Murray",
		"Andrea Graham", "Liam Bond", "Ian Manning", "Emma Jackson",
		"Felicity Hill", "Heather Dowd", "William Paterson", "Andrea Rees",
		"Julia Scott", "Leonard Lambert", "Angela Murray", "Simon Taylor",
		"Delia Paige", "Yvonne Poole", "Dorothy Cornish", "Ava Newman",
		"Jonathan Clark", "Wanda Abraham", "Owen Baker", "Phil Abraham",
		"Hunter Poole", "Dorothy Marshall", "Austin Quinn", "Audrey Stewart",
		"Eric Freeman", "Vanessa Campbell", "Jennifer Walker", "Stewart Welch",
		"Emily Springer", "Donna Simpson", "Stewart Anderson",
		"Madeleine Buckland", "Jasmine Welch", "Kyle Paterson",
		"Adrian Springer", "Tim Piper", "Isaac Reid", "Joe Walker",
		"Neil Terry", "Michelle MacDonald", "Colin Campbell", "Diana Hemmings",
		"Fiona Henderson", "Neil Lee", "Andrew Vaughan", "Kylie Rutherford",
		"Deirdre Turner", "Ella Dowd", "Carolyn Morgan", "Christian West",
		"Zoe Hughes", "Neil Fisher", "Diane Davidson", "Megan Marshall",
		"Melanie Smith", "Una Vance", "Dan Newman", "Tracey Churchill",
		"Dorothy James", "Carolyn Alsop", "Sue Ince", "Christian Reid",
		"Frank North", "Claire Roberts", "Katty Thomson", "Ellie Downs",
		"Eli Simons", "Sam North", "Carson Morris", "Dusty Allen",
		"Bernice Miller", "Lyra Lyman", "Vander Slater", "Vincent Simpson",
		"Bobby Cornish", "Kali Newman", "Carly Lawrence", "Corey Freese",
		"Luke James", "Caroline Grant", "Franky Flynn", "Vanessa Allan",
		"Sean Baker", "Frank Mills", "Rachel Mackenzie", "Stephen Sanderson",
		"Kimberly Vaughan", "Warren Vaughan", "Sebastian Lyman",
		"Cameron Young", "Harry McGrath", "Thomas Langdon", "Benjamin Turner",
		"Anthony Murray", "Anna Miller", "Kevin Black", "Chloe Nolan",
		"Michelle Hodges", "Dominic Bower", "Simon Paige", "Sebastian Murray",
		"Andrea Graham", "Liam Bond", "Ian Manning", "Emma Jackson",
		"Felicity Hill", "Heather Dowd", "William Paterson", "Andrea Rees",
		"Julia Scott", "Leonard Lambert", "Angela Murray", "Simon Taylor",
		"Delia Paige", "Yvonne Poole", "Dorothy Cornish", "Ava Newman",
		"Jonathan Clark", "Wanda Abraham", "Owen Baker", "Phil Abraham",
		"Hunter Poole", "Dorothy Marshall", "Austin Quinn", "Audrey Stewart",
		"Eric Freeman", "Vanessa Campbell", "Jennifer Walker", "Stewart Welch",
		"Emily Springer", "Donna Simpson", "Stewart Anderson",
		"Madeleine Buckland", "Jasmine Welch", "Kyle Paterson",
		"Adrian Springer", "Tim Piper", "Isaac Reid", "Joe Walker",
		"Neil Terry", "Michelle MacDonald", "Colin Campbell", "Diana Hemmings",
		"Fiona Henderson", "Neil Lee", "Andrew Vaughan", "Kylie Rutherford",
		"Deirdre Turner", "Ella Dowd", "Carolyn Morgan", "Christian West",
		"Zoe Hughes", "Neil Fisher", "Diane Davidson", "Megan Marshall",
		"Melanie Smith", "Una Vance", "Dan Newman", "Tracey Churchill",
		"Dorothy James", "Carolyn Alsop", "Sue Ince", "Christian Reid",
		"Frank North", "Claire Roberts", "Gordon Mertz", "Adell Jacobi",
		"Ariana Baily", "Eli Simons", "Sam North", "Carson Morris",
		"Dusty Allen", "Alice Hoffman", "Trinity Barton", "Gavin Slater",
		"Mason Simpson", "Bobby Cornish", "Gabriel Newman", "Ethan Lawrence",
		"Corey Freese", "Jacob James", "Ryan Grant", "Frank Flynn",
		"Jayden Allan", "Noah Baker", "Landon Mills", "William Mackenzie",
		"Stephen Sanderson", "Manny Moore", "Warren Vaughan", "Sebastian Lyman",
		"Cameron Young", "Harry McGrath", "Thomas Langdon", "Benjamin Turner",
		"Anthony Murray", "Anna Miller", "Kevin Black", "Chloe Nolan",
		"Michelle Hodges", "Dominic Bower", "Simon Paige", "Sebastian Murray",
		"Andrea Graham", "Liam Bond", "Ian Manning", "Emma Jackson",
		"Felicity Hill", "Heather Dowd", "William Paterson", "Andrea Rees",
		"Julia Scott", "Leonard Lambert", "Angela Murray", "Simon Taylor",
		"Delia Paige", "Yvonne Poole", "Dorothy Cornish", "Ava Newman",
		"Jonathan Clark", "Wanda Abraham", "Owen Baker", "Phil Abraham",
		"Hunter Poole", "Dorothy Marshall", "Austin Quinn", "Audrey Stewart",
		"Eric Freeman", "Vanessa Campbell", "Jennifer Walker", "Stewart Welch",
		"Emily Springer", "Donna Simpson", "Stewart Anderson",
		"Madeleine Buckland", "Jasmine Welch", "Kyle Paterson",
		"Adrian Springer", "Tim Piper", "Isaac Reid", "Joe Walker",
		"Neil Terry", "Michelle MacDonald", "Colin Campbell", "Diana Hemmings",
		"Fiona Henderson", "Neil Lee", "Andrew Vaughan", "Kylie Rutherford",
		"Deirdre Turner", "Ella Dowd", "Carolyn Morgan", "Christian West",
		"Zoe Hughes", "Neil Fisher", "Diane Davidson", "Megan Marshall",
		"Melanie Smith", "Una Vance", "Dan Newman", "Tracey Churchill",
		"Dorothy James", "Carolyn Alsop", "Sue Ince", "Christian Reid",
		"Frank North", "Clara Watson", };

#endif /* SRC_MAIN_FAKESTUDENTNAMES_H_ */
